version: '3.4'

services:

  ros-master:
    build: ./master
    image: ros-master
    ports:
    - 9090:9090
    expose:
    - 9090
#    command: stdbuf -o L roslaunch rosbridge_server rosbridge_websocket.launch
    command: stdbuf -o L roscore
  #
  ros-bridge:
    image: ros-master
    expose:
    - 9090
    environment:
    - "ROS_MASTER_URI=http://ros-master:11311"
    - "ROS_HOSTNAME=ros-bridge"
    command: stdbuf -o L roslaunch rosbridge_server rosbridge_websocket.launch
    depends_on:
    - ros-master

  package:
    build: ./package
    environment:
    - "ROS_BRIDGE_URI=http://ros-bridge"
    command: python package.py
    depends_on:
    - ros-bridge
    links:
    - ros-bridge
