FROM ros:indigo-ros-core

RUN apt-get update -yqq \
  && apt-get install -yqq --no-install-recommends \
  ros-indigo-rosbridge-server ros-indigo-tf2-web-republisher

#RUN roslaunch rosbridge_server rosbridge_websocket.launch
#RUN rosrun tf2_web_republisher tf2_web_republisher
