FROM ros:kinetic-ros-core

RUN apt-get update -yqq \
  && apt-get install -yqq --no-install-recommends \
  ros-kinetic-rosbridge-server ros-kinetic-tf2-web-republisher \
  ros-kinetic-gazebo-ros-pkgs ros-kinetic-gazebo-ros-control
